### ISSUE TITLE
wont download

### ISSUE THREAD

**Issue by ghost** [cloudfoundry-incubator/garden-linux#67]
## Todos

Please try the following before submitting the issue:

- [ ] Upgrade Concourse if you are observing a failure in a test
- [ ] Use latest BOSH stemcell if the problem occurred in a BOSH VM
- [ ] Use Go 1.5 if the issue has to do with running unit tests locally

## Description

Describe the issue.

## Logging and/or test output

Provide any output you think may help understanding further the issue. Guardian
stores its log files in `/var/vcap/sys/log/garden` when run through its BOSH
release.

## Steps to reproduce

Outline the steps to test or reproduce the PR here. Please also provide the
following information if applicable:

* Garden Linux release version
* Linux kernel version
* Concourse version
* Go version

**Comment by julz** [comment]
Hi @theprogram2 - garden-linux has been deprecated and unsupported for a super super super long time now. I’d suggest moving over to [garden-runc](http://GitHub.com/cloudfoundry/garden-runc-release).
